### PR TITLE
Fix the SDK path expansion error on the Linux platform.

### PR DESCRIPTION
**Pull request by hxcliff**

### CODE REVIEW

**Comment by hxcliff** [comment]
@makepaddev Hey, how's it going?

**Comment by hxcliff** [comment]
> @makepaddev Hey, how's it going?

I can turn it off if you're the one who's been refactoring this part lately.

**Comment by univerz** [comment]
lgtm

@makepaddev this fixes
```      
$ cargo-makepad android toolchain-install
...
Got error: File not found in zip NDK/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/14.0.7/lib/linux/aarch64/libunwind.a
```
on linux

**Comment by makepaddev** [comment]
Hey yea i just refactored / fixed this, did i fix it wrong?

**Comment by makepaddev** [comment]
Merged it, if it works now it works.

**Pull request merged**
