### PR TITLE
Rename 'Size' to 'Length'.

### PR DESCRIPTION
**Pull request by coolbluewater**

### CODE REVIEW

**Comment by makepaddev** [comment]
Hey i didn't agree yet to rename Turtle to Box. And Length i might want Len. Hold horses for just a little while.

**Comment by makepaddev** [comment]
We also have a team and people building things, and i'll bounce these things around first for a day or two.

**Comment by makepaddev** [comment]
Also having to use r#box is hella ugly so that one is out immediately.

**Comment by makepaddev** [comment]
I've been explaining Turtle now for a while and we have docs as well. And no matter how much you disagree the thing DOES walk.

**Comment by makepaddev** [comment]
I'm going to reflect on this for a bit

**Comment by coolbluewater** [comment]
Sigh.

**Comment by makepaddev** [comment]
Yea come on, we have quite a bunch of people coding for a while now building apps. I'm going to bounce this idea around, you might be right. However give it a bit of time.

**Comment by makepaddev** [comment]
Going to see if explanations become clearer, if it sticks if we explain it as Box, etc.

**Comment by makepaddev** [comment]
and rbox would then be get_box or something, current_box. Anyway give it a bit.

**Comment by makepaddev** [comment]
Also Walk might be BoxSize
Layout BoxLayout
and i feel that Width::Fill and Height::Fill are nicer than Length::Fill because thats how i would talk about it. 
Anyway going to bounce it a bit.

**Comment by makepaddev** [comment]
I do like the idea of saying that we have a 'boxmodel'. Thats amassive less 'wtf' than turtle.

**Comment by makepaddev** [comment]
Let me do this rename myself, but give it a bit to let me evolve the naming

**Comment by coolbluewater** [comment]
Why not accept this PR and make the smaller changes on top of that? Serious question - are you an NIH? Because I don't work with such folks.

**Comment by makepaddev** [comment]
Because we have many more repos 'not' this that need to be updated. So i wanna do this change once.

**Comment by makepaddev** [comment]
And yea of course makepad is very heavily NIH in terms of dependencies, we've been writing 90% of what makes makepad tick. But i'm not immune to having arguments about naming, and we CAN still change things arbitrarily mostly and i've already accepted plenty pullrequest. So have a bit of patience when you barge into someone elses 4-5 year old project and propose breaking namechanges that impact many other repos. I'm happy to do it, but i first wanna talk to the team and testdrive the docs naming a bit.

**Comment by coolbluewater** [comment]
Hey, I don't like being barked at. Did we or did we not conclude that Size should be renamed 'Length'? 
I have no idea what you mean by "the thing does walk" since you never defined "walk" without using the word "walk" even though I was metaphorically pulling my hair out. Same for turtle. If your English skills are poor, sorry that's not my problem. You could say "the thing does fart" and I still wouldn't know what you mean.

I make it a point to stick with the technology and never get personal. You've crossed a line for me with 'barge'. If you can't handle the speed at which I like to do things, then this sadly isn't going to work. Just never, ever, take your frustrations out on me.

**Comment by makepaddev** [comment]
Renaming the turtle use is extremely invasive to a LOT of code and muscle memory. So it should happen once and only after some deliberation. Otherwise your input is welcome as you can see.

**Comment by makepaddev** [comment]
Its barely monday, we have a team. Come on. I dont change out fundamental naming underneath peoples work like that. And yea you do have an abrasiveness. Which is fine, i'm abrasive too. So if you can't take a little pushback its not going to work no.

**Comment by coolbluewater** [comment]
No, I challenge you to show my abrasiveness. Intense, yes, personal and rude, no.

**Comment by coolbluewater** [comment]
And if you can't apologize right now for your offensive language, that tells me all I need to know about your collaboration style and ability to admit error, and we can end this right here. Nothing is worth this nonsense.

**Comment by makepaddev** [comment]
Here is where you cross a line: 
Why not accept this PR and make the smaller changes on top of that? Serious question - are you an NIH? Because I don't work with such folks.

I explain clearly why im not immediately introducing a breaking change i might wanna change around a bit,and then you threaten to leave. Thats in my world a form of abrasiveness and agressive behavior. 

Anyway. As i said, im deliberating the change. And if you can't take a bit of pushback around this it's going to be tough.

**Comment by coolbluewater** [comment]
"Threaten to leave" - wow. I'm not your employee. That's it I'm afraid. We're done.

**Comment by makepaddev** [comment]
Ok, well thanks for your input, it's been a short and eventful interaction. I'm sorry for the use of the word barge. But you have to have some reflection on how you are percieved as well in these situations.

**Comment by makepaddev** [comment]
Breaking changes like this i need to have atleast a normal working day or two to deliberate with my team, maybe tweak some naming and only then commit. I already agreed that Box is likely better than Turtle but if you can't give me space to deliberate and reflect on something that literally affects ALL UI code people have written and are writing. It'l be tough sailing.

**Comment by makepaddev** [comment]
Breaking changes like this you do once, people update their thing. If we have to 'iterate' on changes like this and we'll change it twice or three times that is not handy, and especially not on a monday morning without a single announcement or involvement.

**Comment by coolbluewater** [comment]
>Ok, well thanks for your input, it's been a short and eventful interaction. I'm sorry for the use of the word barge. But you have to have some reflection on how you are percieved as well in these situations.

You're only reconfirming your character. Not gracious, not truly polite or thankful. Lip service. 

Look, good luck with your project. I'm already going ahead with my version of the repo and will hard-fork at some point. It's too bad that we're not able to work together and that decision isn't going to change for me. But I have learned quite a bit from this very interesting approach, and in fact got into Rust seriously three years ago because of this project. So I will always be grateful to you for this. 

But the red flags around you at this point are too many - I honestly don't think you understand how to execute deftly in an ever-changing world, that is, how to pivot. I like to work with people several levels above me in multiple dimensions. And most importantly your lack of mental clarity and focus is at this point not something I wish to put up with. Statements like "The thing does walk" are so foggy and bumbling, as was your punt to AI of accessibility. 

I look back at the Q&A from three years ago, of the things you promised were just around the corner - you're still promising those things are just around the corner. Your methodology of no tests virtually guarantees failure, as does the lack of comments. All the great developers I've studied (yes, I actually study developers) without exception *depend* on their own comments heavily.

The terminology you're using also reflects an unfamiliarity with other systems. Maybe that's been an advantage in one respect - it left you free to innovate on this interesting technique of rendering - but there's just too many areas you don't know and *haven't* innovated on, and have basically an "editor" that is unusable. I do hope that somehow changes. But I won't be back.

Take care.

**Comment by makepaddev** [comment]
I have put in hours of work on a sunday to facilitate you working with the stack, i've accepted non-breaking pull requests immediately, and i'm deliberating the terminology changes you proposed nearly immediately (it will take what, 2 days?). I dont know what else to do to keep you happy. But i tried. Good luck with your endeavours.

**Comment by coolbluewater** [comment]
I, I, I, I, right?

**Comment by coolbluewater** [comment]
Let's just leave it at that, shall we. I really have nothing else to say.

**Pull request closed without merging**
